### ISSUE TITLE
full-borders: non-rounded borders option/instruction 

### ISSUE THREAD

**Issue by dangooddd** [yazi-rs/plugins#10]
### Please describe the problem you're trying to solve

Currently there is zero documentation on how to make borders non-round. In previous non-plugin realization you can manually remove round corners in lua code, but now plugin should provide methods to do that (like round = false variable or so) 

### Would you be willing to contribute this feature?

- [x] Yes, I'll give it a shot

### Describe the solution you'd like

Provide method to use non-round borders via full-borders plugin. If this currently exist, add documentation in README of this plugin, because now it is not intuitive

**Comment by sxyazi** [comment]
Nice to have, anyone want to give it a go?

**Comment by dangooddd** [comment]
I implement this (solution may be not the best), will open pull request soon

**Comment by sxyazi** [comment]
Done in https://github.com/yazi-rs/plugins/pull/11, thanks!
