### ISSUE TITLE
Plugin Installation Issues on zsh

### ISSUE THREAD

**Issue by GianniBYoung** [yazi-rs/plugins#12]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

kitty 35.2

### Describe the bug

When using the Z Shell (zsh) the `#` character denotes comments so the listed install command for each plugin is failing.

This can be remediated by escaping the `#` with a `\` -> `\#`

or by simply quoting the plugin -> `ya pack -a 'yazi-rs/plugins#chmod'`

### Expected Behavior

The plugin is found and installed

### To Reproduce

using zsh run the command as listed in documentation -> `ya pack -a yazi-rs/plugins#chmod`

**Comment by sxyazi** [comment]
I can't reproduce it

https://github.com/user-attachments/assets/b51d4624-5068-41e8-b271-adc77e8f7b76

What's your zsh version? Did you use any plugins? If it works without any customizations (start with `zsh -df`)?

**Comment by GianniBYoung** [comment]
ahhhh, you are right. Sorry for the false report.

It seems to be that I have `nomatch` set and zsh is interpreting the # as a pattern.

![image](https://github.com/user-attachments/assets/e2476af7-1fac-44d9-a7fa-8072606a7ec4)

**Comment by sxyazi** [comment]
Nice to see you found the cause of the problem! Let's close the issue then.
