### ISSUE TITLE
ya "pack" subcommand doesn't exist?

### ISSUE THREAD

**Issue by Gh0stGames** [yazi-rs/plugins#13]
### What system are you running Yazi on?

Linux X11

### What terminal are you running Yazi in?

alacritty 0.13.2

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####
Yazi
    Version: 0.2.5 (Arch Linux 2024-04-27)
    OS: linux-x86_64 (unix)
    Debug: false

Emulator
    Emulator.via_env: ("alacritty", "")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect: Unknown([])

Adaptor
    Adaptor.matches: X11

Desktop
    XDG_SESSION_TYPE: Some("x11")
    WAYLAND_DISPLAY: None
    DISPLAY: Some(":1")

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL: Some("/usr/bin/fish")
    EDITOR: Some("helix")
    ZELLIJ_SESSION_NAME: None
    YAZI_FILE_ONE: None
    YAZI_CONFIG_HOME: None

file(1)
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "file-5.45\nmagic file from /usr/share/file/misc/magic\nseccomp support included\n", stderr: "" })

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

tmux
    TMUX: false

Ueberzug++
    Version: Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "ueberzugpp 2.9.6\n", stderr: "" })


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

I was trying to install a plugin mentiooned on the [Yazi tips page](https://yazi-rs.github.io/docs/tips) but apparently the "ya pack" subcommand doesn't exist. I didn't try the nightly build because I didn't think it was necessary to have the "pack" subcommand.

### Expected Behavior

I expected the installation method mentioned on the plugin page would work.

### To Reproduce

Try running "ya pack -a yazi-rs/plugins#max-preview"

### Configuration

all defaults.

### Anything else?

![image](https://github.com/user-attachments/assets/f8961f87-7aea-4f65-addd-7dfe0c3e1cac)

**Comment by sxyazi** [comment]
> I didn't try the nightly build because I didn't think it was necessary to have the "pack" subcommand

Yes, it's needed for the nightly atm, see the README here https://github.com/yazi-rs/plugins?tab=readme-ov-file#plugins

Or you can wait for the 0.3 releases (should be this week). Closing as not bug.

**Comment by Gh0stGames** [comment]
Cool, thank you.
