### ISSUE TITLE
git.yazi ignore is very misleading

### ISSUE THREAD

**Issue by AnirudhG07** [yazi-rs/plugins#18]
### What system are you running Yazi on?

macOS

### What terminal are you running Yazi in?

iTerm

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####

Yazi
    Version: 0.3.2 (69e7c8f 2024-08-30)
    Debug  : false
    OS     : macos-aarch64 (unix)

Ya
    Version: 0.3.2 (69e7c8f 2024-08-30)

Emulator
    Emulator.via_env: ("xterm-256color", "iTerm.app")
    Emulator.via_csi: Ok(Iterm2)
    Emulator.detect : Iterm2

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    /proc/sys/fs/binfmt_misc/WSLInterop: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : Some("/Users/anirudhgupta/dotfiles/yazi/.config/yazi")

Text Opener
    default: Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:=vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : 3.4
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.41
    ueberzugpp       : 2.9.2
    ffmpegthumbnailer: 2.2.2
    magick           : 7.1.1-36
    fzf              : 0.54.3
    fd               : 10.1.0
    rg               : 14.1.0
    chafa            : 1.14.2
    zoxide           : 0.9.4
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.6


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/Users/anirudhgupta/.local/state/yazi" directory.



```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried

### Describe the bug

The ignore `.` of git.yazi is a bit misleading. For example -
Here, in the beginning you can see src with a `.`, I would think it's in .gitignore, but rather some files inside have those properties. It might be intentional to leave it for the case of `M` or `?`, which is good.

https://github.com/user-attachments/assets/35d5f177-ac6b-417d-84ef-717cc84768b3

### Expected Behavior

Not show `.`, even if inside ones have only `.`. It would be better to make it optional for people. 

### To Reproduce

NA

### Configuration

whatever is downloaded with `ya pack` and suggested fetcher addition, etc.

**Comment by TobisLee** [comment]
Sorry to bother the closed issue.

I think this plugin should show ignore sign. As for this case, I don't understand why the plugin is considered misleading? The behavior itself seems misleading, doesn't it? If some files in the src folder aren't ignored, then the src folder shouldn't be ignored either.

**Comment by AnirudhG07** [comment]
U might think src is in gitignore. But only the cache are in gitignore. This is why said u might think something else in regular course of work
