### ISSUE TITLE
Changing git.yazi icons and colors

### ISSUE THREAD

**Issue by GrzegorzKozub** [yazi-rs/plugins#21]
### Please describe the problem you're trying to solve

I saw the references to the `THEME` global but I can't figure out how to configure custom icons and colors.

https://github.com/yazi-rs/plugins/blob/549d76614d303a5d8dc6196296c875172a904a62/git.yazi/init.lua#L110-L127

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

Can you provide an example, please?

**Comment by sxyazi** [comment]
These variables are reserved as Yazi doesn't support them yet, I can add them later.

Also, if you have any suggestions for icons/colors, feel free to share, and I'll consider setting them as the default.

**Comment by GrzegorzKozub** [comment]
Thanks! I can wait for Yazi to support customizing them as my preferences are, of course, not necessarily other people ones.

**Comment by sxyazi** [comment]
Done in https://github.com/yazi-rs/plugins/commit/0b9f325fe9d1edbc6d7893344cd308533ebd827a, doc https://github.com/yazi-rs/plugins/tree/main/git.yazi#advanced
