### ISSUE TITLE
Suggestions for git.yazi icons

### ISSUE THREAD

**Issue by mikavilpas** [yazi-rs/plugins#23]
### Please describe the problem you're trying to solve

I set up some nice icons for the git plugin statuses. Maybe these would make nice defaults in the documentation too.

<img width="665" alt="image" src="https://github.com/user-attachments/assets/b8ab9081-961a-4a55-bbf8-4b770e675318">

### Would you be willing to contribute this feature?

- [ ] Yes, I'll give it a shot

### Describe the solution you'd like

```lua
THEME.git_added_sign = ""
THEME.git_modified_sign = ""
THEME.git_ignored_sign = ""
THEME.git_deleted_sign = ""
THEME.git_untracked_sign = ""

-- TODO what is this?
-- THEME.git_updated_sign = ""
```

### Additional context

I don't know what the "updated" one is used for, but some of the icons are from here https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/init.lua#L53-L55

**Comment by mikavilpas** [comment]
Here are some examples of what they look like

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/ab05a52b-f8d1-4c6b-8afc-baf262f6a4dd">

Is there a way to get the deleted sign to work?

**Comment by sxyazi** [comment]
> I don't know what the "updated" one is used for

"updated" corresponds to "U" in `git status`, i.e. U = updated but unmerged, https://git-scm.com/docs/git-status#:~:text=U%20%3D%20updated%20but%20unmerged

> Is there a way to get the deleted sign to work?

If you delete some files in a folder then it'll work and show up on the folder itself
