### ISSUE TITLE
`git.yazi`: `.git` can be a file when using worktrees.

### ISSUE THREAD

**Issue by metakosmo** [yazi-rs/plugins#29]
### What system are you running Yazi on?

Windows

### What terminal are you running Yazi in?

wezterm

### `yazi --debug` output

<details>

```sh
##### ↓↓↓ Paste the output here: ↓↓↓ #####


```

</details>

### Did you try the latest nightly build to see if the problem got fixed?

No, and I'll explain why below

### Describe the bug

`yazi.git` tries to determine the root directory by looking for a `.git` directory, and skips over files.  But if one is working within a worktree, `.git` is a file which refers to the location of the git repo, like `gitdir: /path/to/git/repo`.

### Expected Behavior

Accept a file `.git` as the marker for the root directory when searching back for one.

### To Reproduce

Create a git worktree that uses a `.git` file to refer to it's repo.

**Comment by sxyazi** [comment]
Please try https://github.com/yazi-rs/plugins/commit/4fcd737db5f6cd4b5d6645659b16d891e1d93dd3

**Comment by metakosmo** [comment]
That works for me.  Thanks.
