### ISSUE TITLE
`full-border` + `max-preview`: visual artefacts in upper/lower left corners of a maximised preview pane

### ISSUE THREAD

**Issue by VKondakoff** [yazi-rs/plugins#3]
There are visual artefacts in upper/lower left corners of a maximised preview pane when using with `full-border` plugin:

<img width="457" alt="Снимок экрана 2024-06-25 в 09 45 54" src="https://github.com/yazi-rs/plugins/assets/230824/70ce5115-852d-4b61-80c3-2d2df5d61a7e">

Just a cosmetic issue, but worth looking to in the name of perfection... ;)

macOS Sonoma 14.5
iTerm2 3.5.2

**Comment by sxyazi** [comment]
Maybe we can check if we should stop applying these character patches when there are only two columns:

https://github.com/yazi-rs/plugins/blob/a882e3828cdeee243ede2bff0524cbe7e27104cf/full-border.yazi/init.lua#L17-L20

Do you want to raise a PR for it?

**Comment by VKondakoff** [comment]
Sorry, I'm not a programmer. Just an experienced tester. So - no PRs from my side.
