### ISSUE TITLE
The `diff` plugin sometimes not copy the content to system clipboard

### ISSUE THREAD

**Issue by TobisLee** [yazi-rs/plugins#30]
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

foot 1.19.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (5eabd7d8 2024-10-28)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (5eabd7d8 2024-10-28)

Emulator
    Emulator.via_env: ("foot", "")
    Emulator.via_csi: Ok(Foot)
    Emulator.detect : Foot

Adapter
    Adapter.matches: Sixel

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-0")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/fish")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : 2.9.6
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-39
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : 1.14.2
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/tlss/.local/state/yazi" directory.
```

### Describe the bug

The `diff` plugin sometimes doesn't copy the content to system clipboard but yazi shows the copy to clipboard message.

I use `Ctrl+f` instead `Ctrl+d`
[屏幕录像_20241030_011013.webm](https://github.com/user-attachments/assets/d88897b3-2e29-4198-b7cc-fb7a99855888)

### Minimal reproducer

1. open yazi
2. select two files
3. use `diff` shortcut to copy content
4. quit yazi
5. see if content was copied to clipboard

**Comment by sxyazi** [comment]
Have you installed [xclip](https://github.com/astrand/xclip) / [wl-clipboard](https://github.com/bugaevc/wl-clipboard) / [xsel](https://github.com/kfish/xsel)? https://yazi-rs.github.io/docs/installation

**Comment by TobisLee** [comment]
Yeah, I have installed `wl-clipboard`

**Comment by sxyazi** [comment]
That's weird, I can't reproduce it, could you debug it a bit please, ex calling [`ya.clipboard()`](https://yazi-rs.github.io/docs/plugins/utils/#ya.clipboard) in a plugin to see if it works along. This is the impl code of `ya.clipboard()`:

https://github.com/sxyazi/yazi/blob/81b8c89ec15f4a1c5e5aa7450e994c3d23ee8597/yazi-plugin/src/utils/text.rs#L52-L62

**Comment by TobisLee** [comment]
I tested the `ya.clipboard()` in my plugin with or without `ya.notify()` function, but both work fine.

After I add the sleep function to the end of the diff plugin, I feel this bug appears more frequently. But it still not a 100% reproduce way.
```lua
		ya.clipboard(output.stdout)
		info("Diff copied to clipboard")
		ya.sleep(0.5)
```

**Comment by sxyazi** [comment]
Still can't reproduce with the `ya.sleep()`, I *guess* it may be a `wl-copy` problem, did you try calling it from your terminal to see if it's working?

**Comment by TobisLee** [comment]
I tested with `wl-copy`, it works fine. Can you be more specific?

![image](https://github.com/user-attachments/assets/df80d8dc-212b-43ec-989c-03b46256b879)

**Comment by sxyazi** [comment]
I don't have a Wayland handy for testing. 

If possible, it'd be best to debug it in Rust to see what's going on

**Comment by TobisLee** [comment]
Okay, I will debug it in weekend.

**Comment by TobisLee** [comment]
I add `info(output.stdout)` before `ya.clipboard`. It seems the diff tool generate empty text sometime.

![图片](https://github.com/user-attachments/assets/069f35c1-2598-48cf-9178-a4de8a7438d1)

![图片](https://github.com/user-attachments/assets/10d2ec6c-cac3-4645-b9f0-b6eec4447b90)

**Comment by sxyazi** [comment]
Print out the full diff command and run it in your terminal to see what happens

**Comment by TobisLee** [comment]
I think I might misunderstand the usage of this plugin :(, it will diff the selceted file and the hovered file, but I always select two files and use diff. Sorry for your time.
