### ISSUE TITLE
Hide preview plugin starts background process, but never completes, doesn't hide previews.

### ISSUE THREAD

**Issue by stibinator** [yazi-rs/plugins#37]
### What system are you running Yazi on?

Linux X11 i3wm

### What terminal are you running Yazi in?

kitty 0.37.0

### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-kitty", "")
    Emulator.via_csi: Ok(Kitty)
    Emulator.detect : Kitty

Adapter
    Adapter.matches: Kitty

Desktop
    XDG_SESSION_TYPE           : Some("x11")
    WAYLAND_DISPLAY            : None
    DISPLAY                    : Some(":1")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/bin/zsh")
    EDITOR             : Some("/usr/bin/nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.46
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-41
    fzf              : 0.56.3
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : 24.09
    jq               : 1.7.1


--------------------------------------------------
```

### Describe the bug

I have installed the hide-preview plugin as per the instructions, and added 
```[[manager.prepend_keymap]]
on   = "#"
run  = "plugin hide-preview"
desc = "Hide or show preview"
```
to my keymap.conf
When I press the appropriate key, the preview is not hidden, but a process indicator appears in the yazi status bar at the bottom, and when I quit yazi I get a notification about processes running.

![screenshot-20241212-111130Z](https://github.com/user-attachments/assets/c1ef1a50-16c9-44f5-bc78-768d2f0a47dc)
![screenshot-20241212-110844Z](https://github.com/user-attachments/assets/5c855205-a086-45a6-a00a-8519291dc5cc)

### Minimal reproducer

To reproduce:
install hide preview plugin
```ya pack -a yazi-rs/plugins:hide-preview```
add keymap to ~/.config/yazi/keymap.toml
```[[manager.prepend_keymap]]
on   = "#"
run  = "plugin hide-preview"
desc = "Hide or show preview"
```

hit # (or whatever key you've set up, I tried a few in case it was because of a conflict).
expected: previews are hidden, like it says on the tin
observed: previews not hidden, background process notifications that never complete. Nothing in log file.

**Comment by sxyazi** [comment]
>     Version: 0.3.3 (Arch Linux 2024-09-05)

Please make sure you're on the latest nightly, or at least the latest stable version 0.4.1

https://github.com/yazi-rs/plugins/blob/62f078905b4de55f19e328452c8a1f889ff2f6f4/README.md?plain=1#L1-L4

**Comment by sxyazi** [comment]
https://github.com/sxyazi/yazi/releases/tag/nightly

**Comment by stibinator** [comment]
Thanks. I'd just installed it through pacman.
