### ISSUE TITLE
use `THEME.manager.border_style.fg` as full-border color

### ISSUE THREAD

**Issue by ocl2go** [yazi-rs/plugins#7]
### Please describe the problem you're trying to solve

Currently, the theme settings don't allow changing the `full-border.yazi` color, which is something I'd like to customize.

<img width="564" alt="before" src="https://github.com/yazi-rs/plugins/assets/106097501/ec11ec49-4e50-4ebd-b429-bdc179445a28">

I want to be able to change the `full-border.yazi` color using the theme setting `THEME.manager.border_style.fg`.

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

fix: Update the full-border.yazi/init.lua to apply the theme setting

```diff
local function setup()
	Manager.render = function(self, area)
		local c = self:layout(area)

		local bar = function(c, x, y)
			if x <= 0 or x == area.w - 1 then
				return {}
			end

			return ui.Bar(
				ui.Rect { x = x, y = math.max(0, y), w = ya.clamp(0, area.w - x, 1), h = math.min(1, area.h) },
				ui.Bar.TOP
			):symbol(c)
		end

+		local border_style = ui.Style():fg(THEME.manager.border_style.fg or "")
+
		return ya.flat {
			-- Borders
-			ui.Border(area, ui.Border.ALL):type(ui.Border.ROUNDED),
+			ui.Border(area, ui.Border.ALL):type(ui.Border.ROUNDED):style(border_style),
-			ui.Bar(c[1]:padding(ui.Padding.y(1)), ui.Bar.RIGHT),
+			ui.Bar(c[1]:padding(ui.Padding.y(1)), ui.Bar.RIGHT):style(border_style),
-			ui.Bar(c[3]:padding(ui.Padding.y(1)), ui.Bar.LEFT),
+			ui.Bar(c[3]:padding(ui.Padding.y(1)), ui.Bar.LEFT):style(border_style),

			bar("┬", c[1].right - 1, c[1].y),
			bar("┴", c[1].right - 1, c[1].bottom - 1),
			bar("┬", c[2].right, c[2].y),
			bar("┴", c[2].right, c[2].bottom - 1),

			-- Parent
			Parent:render(c[1]:padding(ui.Padding.xy(1))),
			-- Current
			Current:render(c[2]:padding(c[1].w > 0 and ui.Padding.y(1) or ui.Padding(1, 0, 1, 1))),
			-- Preview
			Preview:render(c[3]:padding(ui.Padding.xy(1))),
		}
	end
end

return { setup = setup }
```

### Additional context

With this change, the border color will update as shown below:

<img width="570" alt="after" src="https://github.com/yazi-rs/plugins/assets/106097501/462d0029-00f5-42d0-8a77-34da836ad7c6">

**Comment by sxyazi** [comment]
Sounds good to me! Please raise a PR for it.
